//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicMark
    {
        public string StudentID { get; set; }
        public string DisciplineID { get; set; }
        public Nullable<double> ProcessMark { get; set; }
        public Nullable<double> MidtermMark { get; set; }
        public Nullable<double> FinaltermMark { get; set; }
        public Nullable<double> AvarageMark { get; set; }
        public Nullable<bool> DisciplineStatus { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Student Student { get; set; }
        //abc
    }
}
