//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorMark
    {
        public string StudentID { get; set; }
        public string ActivityName { get; set; }
        public Nullable<double> Point { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> FinishDay { get; set; }
        public string isHappen { get; set; }
        public Nullable<int> MaxParticipation { get; set; }
        public Nullable<int> RegisteredParticipation { get; set; }
        public string ActivityGroupID { get; set; }
        public string Organization { get; set; }
    
        public virtual ActivityGroup ActivityGroup { get; set; }
        public virtual Student Student { get; set; }
    }
}
