//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiplomaProject1
    {
        public string StudentID { get; set; }
        public string ProjectName { get; set; }
        public string Instructor { get; set; }
        public string Detail { get; set; }
        public string Result { get; set; }
        public string KindOfResearch { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
