//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discipline()
        {
            this.AcademicMark = new HashSet<AcademicMark>();
            this.RegisterStudyUnit = new HashSet<RegisterStudyUnit>();
        }
    
        public string DisciplineID { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> FinishDay { get; set; }
        public string StudyDate { get; set; }
        public string TeacherID { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> AnouncementID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicMark> AcademicMark { get; set; }
        public virtual Anouncement Anouncement { get; set; }
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterStudyUnit> RegisterStudyUnit { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
