//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship
    {
        public string ScholarID { get; set; }
        public string ScholarName { get; set; }
        public string Supplier { get; set; }
        public string ConditionID { get; set; }
    
        public virtual ScholarCondition ScholarCondition { get; set; }
    }
}
