//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyFee
    {
        public string StudentID { get; set; }
        public string SemesterID { get; set; }
        public Nullable<double> PrimaryFee { get; set; }
        public Nullable<int> PlusFee { get; set; }
        public Nullable<bool> isPaid { get; set; }
    
        public virtual PlusFee PlusFee1 { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
