//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentDBEntities : DbContext
    {
        public StudentDBEntities()
            : base("name=StudentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicMark> AcademicMark { get; set; }
        public virtual DbSet<ActivityGroup> ActivityGroup { get; set; }
        public virtual DbSet<BehaviorMark> BehaviorMark { get; set; }
        public virtual DbSet<Candre> Candre { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DiplomaProject> DiplomaProject { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Parents> Parents { get; set; }
        public virtual DbSet<PlusFee> PlusFee { get; set; }
        public virtual DbSet<Policy> Policy { get; set; }
        public virtual DbSet<RegisterStudyUnit> RegisterStudyUnit { get; set; }
        public virtual DbSet<ScholarCondition> ScholarCondition { get; set; }
        public virtual DbSet<Scholarship> Scholarship { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Semester> Semester { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentUser> StudentUser { get; set; }
        public virtual DbSet<StudyFee> StudyFee { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TeacherUser> TeacherUser { get; set; }
        public virtual DbSet<UserImage> UserImage { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<GeneralAnouncement> GeneralAnouncement { get; set; }
        public virtual DbSet<DisciplineAnouncement> DisciplineAnouncement { get; set; }
        public virtual DbSet<UniversityInfo> UniversityInfo { get; set; }
    
        public virtual ObjectResult<GetAcademicByID_Result> GetAcademicByID(string studentID, string module, string year)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var moduleParameter = module != null ?
                new ObjectParameter("Module", module) :
                new ObjectParameter("Module", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAcademicByID_Result>("GetAcademicByID", studentIDParameter, moduleParameter, yearParameter);
        }
    
        public virtual ObjectResult<GetActivities_Result> GetActivities(string groupName)
        {
            var groupNameParameter = groupName != null ?
                new ObjectParameter("GroupName", groupName) :
                new ObjectParameter("GroupName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActivities_Result>("GetActivities", groupNameParameter);
        }
    
        public virtual ObjectResult<GetActivityGroup_Result> GetActivityGroup(string studentID, string module, string year)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var moduleParameter = module != null ?
                new ObjectParameter("Module", module) :
                new ObjectParameter("Module", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActivityGroup_Result>("GetActivityGroup", studentIDParameter, moduleParameter, yearParameter);
        }
    
        public virtual ObjectResult<GetDetailActivity_Result> GetDetailActivity(string activity)
        {
            var activityParameter = activity != null ?
                new ObjectParameter("Activity", activity) :
                new ObjectParameter("Activity", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailActivity_Result>("GetDetailActivity", activityParameter);
        }
    
        public virtual ObjectResult<GetDetailDisciplineByID_Result> GetDetailDisciplineByID(string disciplineID)
        {
            var disciplineIDParameter = disciplineID != null ?
                new ObjectParameter("DisciplineID", disciplineID) :
                new ObjectParameter("DisciplineID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailDisciplineByID_Result>("GetDetailDisciplineByID", disciplineIDParameter);
        }
    
        public virtual ObjectResult<GetDiplomaProject_Result> GetDiplomaProject(string studenID)
        {
            var studenIDParameter = studenID != null ?
                new ObjectParameter("StudenID", studenID) :
                new ObjectParameter("StudenID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDiplomaProject_Result>("GetDiplomaProject", studenIDParameter);
        }
    
        public virtual ObjectResult<GetStudentsInfoByID_Result> GetStudentsInfoByID(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentsInfoByID_Result>("GetStudentsInfoByID", studentIDParameter);
        }
    
        public virtual ObjectResult<GetUser_Result> GetUser(string iD, string passWord)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUser_Result>("GetUser", iDParameter, passWordParameter);
        }
    
        public virtual int ChangeUserPasswork(string newPasswork, string iD)
        {
            var newPassworkParameter = newPasswork != null ?
                new ObjectParameter("newPasswork", newPasswork) :
                new ObjectParameter("newPasswork", typeof(string));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeUserPasswork", newPassworkParameter, iDParameter);
        }
    
        public virtual ObjectResult<GetUsersDetail_Result> GetUsersDetail(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersDetail_Result>("GetUsersDetail", studentIDParameter);
        }
    
        public virtual int AddNewUserImage(string imagePath, byte[] imageToByte, string studentID)
        {
            var imagePathParameter = imagePath != null ?
                new ObjectParameter("ImagePath", imagePath) :
                new ObjectParameter("ImagePath", typeof(string));
    
            var imageToByteParameter = imageToByte != null ?
                new ObjectParameter("ImageToByte", imageToByte) :
                new ObjectParameter("ImageToByte", typeof(byte[]));
    
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddNewUserImage", imagePathParameter, imageToByteParameter, studentIDParameter);
        }
    
        public virtual ObjectResult<IsDateRegister_Result> IsDateRegister()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IsDateRegister_Result>("IsDateRegister");
        }
    
        public virtual ObjectResult<GetStudentAndParentInfoByID_Result> GetStudentAndParentInfoByID(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentAndParentInfoByID_Result>("GetStudentAndParentInfoByID", studentIDParameter);
        }
    
        public virtual int UpdateStudentProfile(string studentID, string parentName, string parentMobile, Nullable<bool> parentGender, string presentAddress, string permanentAddress, string mobile, Nullable<bool> gender)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var parentNameParameter = parentName != null ?
                new ObjectParameter("ParentName", parentName) :
                new ObjectParameter("ParentName", typeof(string));
    
            var parentMobileParameter = parentMobile != null ?
                new ObjectParameter("ParentMobile", parentMobile) :
                new ObjectParameter("ParentMobile", typeof(string));
    
            var parentGenderParameter = parentGender.HasValue ?
                new ObjectParameter("ParentGender", parentGender) :
                new ObjectParameter("ParentGender", typeof(bool));
    
            var presentAddressParameter = presentAddress != null ?
                new ObjectParameter("PresentAddress", presentAddress) :
                new ObjectParameter("PresentAddress", typeof(string));
    
            var permanentAddressParameter = permanentAddress != null ?
                new ObjectParameter("PermanentAddress", permanentAddress) :
                new ObjectParameter("PermanentAddress", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudentProfile", studentIDParameter, parentNameParameter, parentMobileParameter, parentGenderParameter, presentAddressParameter, permanentAddressParameter, mobileParameter, genderParameter);
        }
    
        public virtual ObjectResult<GetClassDetail_Result> GetClassDetail(string classID)
        {
            var classIDParameter = classID != null ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClassDetail_Result>("GetClassDetail", classIDParameter);
        }
    
        public virtual ObjectResult<GetDeparmentDetail_Result> GetDeparmentDetail(string departmentID)
        {
            var departmentIDParameter = departmentID != null ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDeparmentDetail_Result>("GetDeparmentDetail", departmentIDParameter);
        }
    
        public virtual ObjectResult<GetFacultyDetail_Result> GetFacultyDetail(string facultyID)
        {
            var facultyIDParameter = facultyID != null ?
                new ObjectParameter("FacultyID", facultyID) :
                new ObjectParameter("FacultyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFacultyDetail_Result>("GetFacultyDetail", facultyIDParameter);
        }
    
        public virtual ObjectResult<GetSchooltDetail_Result> GetSchooltDetail(string schoolID)
        {
            var schoolIDParameter = schoolID != null ?
                new ObjectParameter("SchoolID", schoolID) :
                new ObjectParameter("SchoolID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSchooltDetail_Result>("GetSchooltDetail", schoolIDParameter);
        }
    
        public virtual ObjectResult<GetListDisciplineForThisUser_Result> GetListDisciplineForThisUser(string thisUser)
        {
            var thisUserParameter = thisUser != null ?
                new ObjectParameter("ThisUser", thisUser) :
                new ObjectParameter("ThisUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListDisciplineForThisUser_Result>("GetListDisciplineForThisUser", thisUserParameter);
        }
    
        public virtual int InsertRegisterStudyUnit(string studentID, string discipline, string semesterID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var disciplineParameter = discipline != null ?
                new ObjectParameter("Discipline", discipline) :
                new ObjectParameter("Discipline", typeof(string));
    
            var semesterIDParameter = semesterID != null ?
                new ObjectParameter("SemesterID", semesterID) :
                new ObjectParameter("SemesterID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertRegisterStudyUnit", studentIDParameter, disciplineParameter, semesterIDParameter);
        }
    
        public virtual ObjectResult<GetUniversityInfo_Result> GetUniversityInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUniversityInfo_Result>("GetUniversityInfo");
        }
    
        public virtual ObjectResult<GetAllGeneralAnouncements_Result> GetAllGeneralAnouncements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllGeneralAnouncements_Result>("GetAllGeneralAnouncements");
        }
    
        public virtual int DeleteRegisterStudyUnit(string studentID, string disciplineID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var disciplineIDParameter = disciplineID != null ?
                new ObjectParameter("DisciplineID", disciplineID) :
                new ObjectParameter("DisciplineID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteRegisterStudyUnit", studentIDParameter, disciplineIDParameter);
        }
    
        public virtual int UpdateStarDay(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStarDay", studentIDParameter);
        }
    
        public virtual ObjectResult<GetInfoDiscipline_Result> GetInfoDiscipline()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoDiscipline_Result>("GetInfoDiscipline");
        }
    
        public virtual ObjectResult<GetInfoRegistered_Result> GetInfoRegistered(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoRegistered_Result>("GetInfoRegistered", studentIDParameter);
        }
    
        public virtual ObjectResult<GetInfoRegistered1_Result> GetInfoRegistered1(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoRegistered1_Result>("GetInfoRegistered1", studentIDParameter);
        }
    
        public virtual ObjectResult<string> GetTeacherRegister()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetTeacherRegister");
        }
    
        public virtual ObjectResult<string> GetDepartmentRegister()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetDepartmentRegister");
        }
    
        public virtual ObjectResult<SortDisciplinebyTeacherAndDepartment_Result> SortDisciplinebyTeacherAndDepartment(string teacherName, string departmentName)
        {
            var teacherNameParameter = teacherName != null ?
                new ObjectParameter("TeacherName", teacherName) :
                new ObjectParameter("TeacherName", typeof(string));
    
            var departmentNameParameter = departmentName != null ?
                new ObjectParameter("DepartmentName", departmentName) :
                new ObjectParameter("DepartmentName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SortDisciplinebyTeacherAndDepartment_Result>("SortDisciplinebyTeacherAndDepartment", teacherNameParameter, departmentNameParameter);
        }
    
        public virtual ObjectResult<GetDateRegisterUnit_Result> GetDateRegisterUnit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDateRegisterUnit_Result>("GetDateRegisterUnit");
        }
    
        public virtual ObjectResult<Nullable<int>> TimeCloseRegisterUnit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TimeCloseRegisterUnit");
        }
    
        public virtual ObjectResult<Nullable<int>> CountGeneralAnouncement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CountGeneralAnouncement");
        }
    
        public virtual ObjectResult<SelectGeneralAnouncementInRange_Result> SelectGeneralAnouncementInRange(Nullable<int> start, Nullable<int> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectGeneralAnouncementInRange_Result>("SelectGeneralAnouncementInRange", startParameter, endParameter);
        }
    
        public virtual ObjectResult<Get10NewestAnouncements_Result> Get10NewestAnouncements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get10NewestAnouncements_Result>("Get10NewestAnouncements");
        }
    
        public virtual ObjectResult<GetGeneralAnoucementDetailByTitle_Result> GetGeneralAnoucementDetailByTitle(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGeneralAnoucementDetailByTitle_Result>("GetGeneralAnoucementDetailByTitle", titleParameter);
        }
    
        public virtual ObjectResult<Get10NewestGeneralAnouncements_Result> Get10NewestGeneralAnouncements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get10NewestGeneralAnouncements_Result>("Get10NewestGeneralAnouncements");
        }
    
        public virtual ObjectResult<Get10NewestDisciplineAnouncements_Result> Get10NewestDisciplineAnouncements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get10NewestDisciplineAnouncements_Result>("Get10NewestDisciplineAnouncements");
        }
    
        public virtual ObjectResult<GetDisciplineAnoucementDetailByTitle_Result> GetDisciplineAnoucementDetailByTitle(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDisciplineAnoucementDetailByTitle_Result>("GetDisciplineAnoucementDetailByTitle", titleParameter);
        }
    
        public virtual ObjectResult<SelectDisciplineAnouncementInRange_Result> SelectDisciplineAnouncementInRange(Nullable<int> start, Nullable<int> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectDisciplineAnouncementInRange_Result>("SelectDisciplineAnouncementInRange", startParameter, endParameter);
        }
    
        public virtual ObjectResult<SelectAnouncementTypeInRange_Result> SelectAnouncementTypeInRange(Nullable<int> start, Nullable<int> end, string type)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAnouncementTypeInRange_Result>("SelectAnouncementTypeInRange", startParameter, endParameter, typeParameter);
        }
    
        public virtual ObjectResult<GetScheduleForDetail1_Result> GetScheduleForDetail1(string studentID, string module, string year, string studyDate, Nullable<double> height, Nullable<double> width)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var moduleParameter = module != null ?
                new ObjectParameter("Module", module) :
                new ObjectParameter("Module", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var studyDateParameter = studyDate != null ?
                new ObjectParameter("StudyDate", studyDate) :
                new ObjectParameter("StudyDate", typeof(string));
    
            var heightParameter = height.HasValue ?
                new ObjectParameter("Height", height) :
                new ObjectParameter("Height", typeof(double));
    
            var widthParameter = width.HasValue ?
                new ObjectParameter("Width", width) :
                new ObjectParameter("Width", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScheduleForDetail1_Result>("GetScheduleForDetail1", studentIDParameter, moduleParameter, yearParameter, studyDateParameter, heightParameter, widthParameter);
        }
    }
}
