//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherUser
    {
        public string ID { get; set; }
        public string Passwork { get; set; }
        public string TeacherID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
